sh cloning_arg.sh Character ID "English"
sh cloning_arg.sh Dave 0 "Gosh Durnit! My basement flooded again!"
sh cloning_arg.sh Dave 41 "I think I have a bucket 'round here somewhere..."
sh cloning_arg.sh Narr 30 "Your bucket is over on the shelf. Click on it to add it to your toolbox."
sh cloning_arg.sh Dave 3 " Not again!"
sh cloning_arg.sh Dave 2 " It's a door to the outside."
sh cloning_arg.sh Dave 12 " I'm not goin nowhere yet"
sh cloning_arg.sh Dave 44 "Oh man... this is going to take forever."
sh cloning_arg.sh Dave 45 "Maybe there's something at Doc's hardware store that can help."
sh cloning_arg.sh Narr 28 "Click on the door to the right to leave your basement."
sh cloning_arg.sh Dave 6 " This bucket ain't gonna cut it..."
sh cloning_arg.sh Dave 5 "That's a lot of water!"
sh cloning_arg.sh Narr 36 "Click the door to leave your basement."
sh cloning_arg.sh Dave 46 " Finally! We got that dang water outta my dang basement!"
sh cloning_arg.sh Dave 47 " I sure hope that never happens again!"
sh cloning_arg.sh Narr 53 " Two weeks later..."
sh cloning_arg.sh Narr 2 "Congratulations! The water level has decreased. However, it is not enough..."
sh cloning_arg.sh Dave 4 " This is too hard!"
sh cloning_arg.sh Dave 15 "I'd better head back to the hardware store."
sh cloning_arg.sh Dave 13 " This dang thang just ain't enough for the major floodage I get here."
sh cloning_arg.sh Dave 14 " At this point, I just want to leave this house."
sh cloning_arg.sh Dave 16 " I should call the realtor for the house up on the hill."
sh cloning_arg.sh Dave 115 " Phew!"
sh cloning_arg.sh Dave 31 " Are you kidding me?!"
sh cloning_arg.sh Dave 33 "That's it."
sh cloning_arg.sh Dave 60 " I'm done."
sh cloning_arg.sh Dave 92 " I ain't puttin up with this dang basement any longer!"
sh cloning_arg.sh Dave 100 "I bet that house up there on the hill has a basement dryer than a desert!"
sh cloning_arg.sh Dave 103 " I oughtta give that real estate agent a call."
sh cloning_arg.sh Dave 118 "It's broken!"
sh cloning_arg.sh Dave 119 " It's that rusty washer."
sh cloning_arg.sh Dave 120 " I'd better put the new washer on."
sh cloning_arg.sh Dave 121 " Whoops, forgot to tighten the washer!"
sh cloning_arg.sh Dave 50 " This pump is busted!"
sh cloning_arg.sh Dave 56 " The valve is leaking, it looks like there's a rusty washer."
sh cloning_arg.sh Dave 57 " I don't have the tools to replace it, I need to go to Doc's."
sh cloning_arg.sh Dave 58 " The valve is leaking, it looks like there's a rusty washer."
sh cloning_arg.sh Dave 59 " I don't have the tools to replace it, I need to go to Doc's."
sh cloning_arg.sh Dave 25 "I'm pooped! I need some extra muscle."
sh cloning_arg.sh Dave 26 "I bet my friend Tony could help out, I should give him a call."
sh cloning_arg.sh Narr 3 "You've chosen the correct parts for the pump and the water level has decreased."
sh cloning_arg.sh Dave 7 "Still not enough... I could use some extra hands."
sh cloning_arg.sh Dave 8 " This isn't any better. I should try different parts."
sh cloning_arg.sh Narr 62 " Rusty washer removed."
sh cloning_arg.sh Dave 122 " Where's that new washer?"
sh cloning_arg.sh Dave 123 " That should do it!"
sh cloning_arg.sh Dave 124 " Whoop, gotta take that rusty old washer off before I can put this shiny new one on."
sh cloning_arg.sh Narr 63 " New washer placed on pump."
sh cloning_arg.sh Tony 0 "Here goes nothing!"
sh cloning_arg.sh Narr 4 " The recruited muscle has helped bring the water level down."
sh cloning_arg.sh Tony 4 " Phew... I'm wiped out. Got any grub?"
sh cloning_arg.sh Dave 34 " Gee Tony, I haven't got any food"
sh cloning_arg.sh Tony 2 " Why don't you give that pizza place a call?"
sh cloning_arg.sh Tony 7 " I could eat an entire pie"
sh cloning_arg.sh Narr 34 "Bucket added to your toolbox."
sh cloning_arg.sh Dave 42 " There it is! Now I can scoop up some of this water."
sh cloning_arg.sh Narr 32 " Click on the bucket icon in your toolbox at the bottom left to select it."
sh cloning_arg.sh Narr 60 "You also have a cell phone, which you can use to call the Hint Hotline."
sh cloning_arg.sh Dave 43 " There's my bucket! I can use that to scoop out the water."
sh cloning_arg.sh Dave 44 "Oh man... this is going to take forever."
sh cloning_arg.sh Dave 45 "Maybe there's something at Doc's hardware store that can help."
sh cloning_arg.sh Narr 37 "Click on a space in the room to walk to it."
sh cloning_arg.sh Dave 30 " This bucket aint going to cut it..."
sh cloning_arg.sh Dave 48 " It's a window. Yup."
sh cloning_arg.sh Dave 49 "It's bleach, fer cleanin' yer clothes."
sh cloning_arg.sh Dave 51 "It's a can of Mach brand orange spray paint."
sh cloning_arg.sh Dave 52 " It's my trusty old washing machine."
sh cloning_arg.sh Dave 35 " Although at this point I probably could just throw some detergent in the water and make my whole basement the washing machine."
sh cloning_arg.sh Dave 53 "This clunker of a boiler is from the 1940's."
sh cloning_arg.sh Dave 36 "  It works, but it makes the worst darn noises you've ever dun heard."
sh cloning_arg.sh Dave 54 "Haven't used this in a while."
sh cloning_arg.sh Dave 37 "For all you kids out there, this is what TV's looked like in the stone age."
sh cloning_arg.sh Dave 55 " I can't believe I thought this looked good."
sh cloning_arg.sh Tony 5 "Pizza AND beer?!"
sh cloning_arg.sh Tony 6 "Just what I needed!"
sh cloning_arg.sh Dave 38 " It's beautiful!"
sh cloning_arg.sh Dave 40 "Like a charm!"
sh cloning_arg.sh Narr 65 " 3 months later"
sh cloning_arg.sh Dave 104 "Hello?"
sh cloning_arg.sh Narr 66 " Hi Dave, your new home is ready!"
sh cloning_arg.sh Dave 131 "Finally!"
sh cloning_arg.sh Dave 40 "Like a charm!"
sh cloning_arg.sh Narr 61 "6 months later..."
sh cloning_arg.sh Dave 113 " Another flood?"
sh cloning_arg.sh Dave 114 "Nothing my Pump-o-matic 5000 can't handle!"
sh cloning_arg.sh Dave 115 " Phew!"
sh cloning_arg.sh Dave 116 " The pump works again!"
sh cloning_arg.sh Dave 117 "Seriously?!"
sh cloning_arg.sh Dave 118 "It's broken!"
sh cloning_arg.sh Dave 119 " It looks like there's a rusty washer."
sh cloning_arg.sh Dave 120 " I'd better put the new washer on."
sh cloning_arg.sh Dave 121 " Whoops, forgot to tighten the washer!"
sh cloning_arg.sh Narr 62 " Rusty washer removed."
sh cloning_arg.sh Dave 122 " Where's that new washer?"
sh cloning_arg.sh Dave 123 " That should do it!"
sh cloning_arg.sh Dave 124 " Whoop, gotta take that rusty old washer off before I can put this shiny new one on."
sh cloning_arg.sh Narr 63 " New washer placed on pump."
sh cloning_arg.sh Dave 125 " Ain't she a beauty?"
sh cloning_arg.sh  0 "Water"
sh cloning_arg.sh  1 "Pump"
sh cloning_arg.sh  2 "Handle"
sh cloning_arg.sh  3 "Bucket"
sh cloning_arg.sh  4 "Hose"
sh cloning_arg.sh  5 "Electric Pump"
sh cloning_arg.sh  6 "Box"
sh cloning_arg.sh  7 "Door"
sh cloning_arg.sh  8 "Window"
sh cloning_arg.sh  9 "Bleach"
sh cloning_arg.sh  10 "Spray Paint"
sh cloning_arg.sh  11 "Washing Machine"
sh cloning_arg.sh  12 "Boiler"
sh cloning_arg.sh  13 "TV"
sh cloning_arg.sh  14 "Couch"
sh cloning_arg.sh Dave 32 " What a trip!"
sh cloning_arg.sh Narr 7 " The Hardware Store"
sh cloning_arg.sh Narr 8 " Home"
sh cloning_arg.sh Narr 9 " Jim's House"
sh cloning_arg.sh Dave 78 "The road is flooded!"
sh cloning_arg.sh Dave 80 " The only other way to Doc's is over that huge hill..."
sh cloning_arg.sh Dave 82 "Better get moving."
sh cloning_arg.sh Dave 84 " What's this?"
sh cloning_arg.sh Dave 86 " The house on the hill is for sale!"
sh cloning_arg.sh Dave 88 " I'm sure whoever lives there doesn't have to deal with any flooding."
sh cloning_arg.sh Dave 90 " Better save the real estate agent's number."
sh cloning_arg.sh Dave 132 " There's my new house"
sh cloning_arg.sh Dave 133 " I can't wait to move in!"
sh cloning_arg.sh Dave 94 " If I lived up there I wouldn't have to deal with any more floods."
sh cloning_arg.sh Dave 96 " Better give that real estate agent a call."
sh cloning_arg.sh  15 "Doc's Hardware"
sh cloning_arg.sh  16 "Home"
sh cloning_arg.sh  17 "New House"
sh cloning_arg.sh Dave 10 "Let's take this back home and see how it works!"
sh cloning_arg.sh Dave 11 "I ain't leavin' til I've got somethin' to get that water outta my basement!"
sh cloning_arg.sh Narr 11 " Beer has been added to your toolbolx."
sh cloning_arg.sh Dave 61 "Used paint?! For only a dollar?! What a steal!"
sh cloning_arg.sh Dave 62 "I wonder what's in there."
sh cloning_arg.sh Dave 63 "Poke a man? Now why would I do that?"
sh cloning_arg.sh Dave 64 "Poke a man? Now why would I do that?"
sh cloning_arg.sh Dave 65 "I wonder what's in there."
sh cloning_arg.sh Dave 66 "Used paint?! For only a dollar?! What a steal!"
sh cloning_arg.sh Dave 67 " Looks POWerful."
sh cloning_arg.sh Dave 68 " Looks POWerful."
sh cloning_arg.sh Dave 69 "Blue rodent not included."
sh cloning_arg.sh Dave 70 "Blue rodent not included."
sh cloning_arg.sh Dave 71 "Oh. That's a pipe bomb."
sh cloning_arg.sh Dave 72 "Oh. That's a pipe bomb."
sh cloning_arg.sh Dave 73 "Lugging that hunk of iron around would be a work out in itself."
sh cloning_arg.sh Dave 74 "Lugging that hunk of iron around would be a work out in itself."
sh cloning_arg.sh Dave 75 "Why so glum, chum?"
sh cloning_arg.sh Dave 76 "Why so glum, chum?"
sh cloning_arg.sh Dave 77 "A box of peanuts, walnuts, and pistachios."
sh cloning_arg.sh Dave 79 "It's filled to the brim with lightning bolts."
sh cloning_arg.sh Dave 81 "It's filled with banjos and kazoos. My favorite instruments!"
sh cloning_arg.sh Dave 83 "A can of red paint. Definitely my favorite color."
sh cloning_arg.sh Dave 85 "A can of orange paint. Definitely my favorite color."
sh cloning_arg.sh Dave 87 "A can of yellow paint. Definitely my favorite color."
sh cloning_arg.sh Dave 89 "A can of green paint. Definitely my favorite color."
sh cloning_arg.sh Dave 91 "A can of blue paint. Definitely my favorite color."
sh cloning_arg.sh Dave 93 "A can of purple paint. Definitely my favorite color."
sh cloning_arg.sh Dave 95 "Lamp Oil."
sh cloning_arg.sh Dave 97 "It's rope. What did you expect?"
sh cloning_arg.sh Dave 99 "I hope he has the correct permits to sell these."
sh cloning_arg.sh Dave 101 "Hey! I'm no chump..."
sh cloning_arg.sh Dave 102 "Am I?"
sh cloning_arg.sh  18 "Door"
sh cloning_arg.sh  19 "Used Paint"
sh cloning_arg.sh  20 "Question Box"
sh cloning_arg.sh  21 "Pokeball"
sh cloning_arg.sh  22 "POW Block"
sh cloning_arg.sh  23 "Gold Ring"
sh cloning_arg.sh  24 "Pipe Bomb"
sh cloning_arg.sh  25 "Buster Sword"
sh cloning_arg.sh  26 "Ghost"
sh cloning_arg.sh  27 "Box of Nuts"
sh cloning_arg.sh  28 "Box of Bolts"
sh cloning_arg.sh  29 "Box of Banjos & Kazoos"
sh cloning_arg.sh  30 "Red Paint"
sh cloning_arg.sh  31 "Orange Paint"
sh cloning_arg.sh  32 "Yellow Paint"
sh cloning_arg.sh  33 "Green Paint"
sh cloning_arg.sh  34 "Blue Paint"
sh cloning_arg.sh  35 "Purple Paint"
sh cloning_arg.sh  36 "Lamp Oil"
sh cloning_arg.sh  37 "Rope"
sh cloning_arg.sh  38 "Bombs"
sh cloning_arg.sh  39 "Sign"
